

model_config:
  name: DeepSpeech2LAS #DeepSpeech2Transducer/DeepSpeech2CTC/DeepSpeech2LAS
  conv_conf:
    conv_type: 2
    conv_kernels: [[11, 41], [11, 21], [11, 11]]
    conv_strides: [[2, 2], [1, 2], [1, 2]]
    conv_filters: [32, 32, 96]
    conv_dropout: 0
  rnn_conf:
    rnn_layers: 5
    rnn_type: lstm
    rnn_units: 512
    rnn_bidirectional: True
    rnn_rowconv: False
    rnn_dropout: 0
  fc_conf:
    fc_units: [512]
    fc_dropout: 0
  Transducer_decoder:
    embed_dim: 144
    embed_dropout: 0.0
    num_lstms: 1
    lstm_units: 320
    joint_dim: 1024
  LAS_decoder:
    n_classes: None
    embedding_hidden_size: 512
    initializer_range: 0.02
    layer_norm_eps: 1e-6
    n_prenet_layers: 2
    prenet_units: 256
    prenet_activation: "mish"
    prenet_dropout_rate: 0.5
    n_lstm_decoder: 1
    decoder_lstm_units: 256
    attention_dim: 128
    attention_filters: 32
    attention_kernel: 31
  enable_tflite_convertible: False #not support True